version: '2'
services:
  catalog:
    build: .
    image: tiagoprn/catalog
    container_name: catalog-api
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: make runserver
    environment:
      PYTHONUNBUFFERED: 0
    ports:
      - "8000:8000"
    logging:
      options:
        max-size: 50m

