# Generated by Django 2.2.2 on 2019-06-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190627_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantssizes',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='pants',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pantssizes',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pantssizes',
            name='pants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pants_sizes', to='core.Pants'),
        ),
        migrations.AlterField(
            model_name='pantssizes',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
